package com.cg.test;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

import org.junit.Test;

import com.cg.entity.Product;

public class TestProduct2 {
	
	

	@Test
	public void testDetached() {
		EntityManagerFactory factory = Persistence.createEntityManagerFactory("MyJPA");
		EntityManager mgr = factory.createEntityManager();
		EntityTransaction txn = mgr.getTransaction();
		txn.begin();
		Product p = (Product) mgr.find(Product.class, 2);
		txn.commit();
		mgr.close();
		
		mgr = factory.createEntityManager();
		txn = mgr.getTransaction();
		txn.begin();
		p.setStock(70);
		mgr.merge(p); // to update existing entity in table
		txn.commit();
		mgr.close();
	}
	
	@Test
	public void testMerge() {
		EntityManagerFactory factory = Persistence.createEntityManagerFactory("MyJPA");
		EntityManager mgr = factory.createEntityManager();
		EntityTransaction txn = mgr.getTransaction();
		txn.begin();
		Product p = new Product();
		//p.setCode(123);// code not found then insert the new one with autogenerated value if found then update value (merge)
		p.setCode(2); // for existing code 
		p.setName("Realme");
		p.setPrice(5000);
		p.setStock(10);
		mgr.merge(p);
		txn.commit();
		mgr.close();
		
	}

}
